### PR TITLE
SQL reorganization and simplification

### PR DESCRIPTION
**Pull request by cmutel**
@tngTUDOR Please check if this seems reasonable

### CODE REVIEW

**Comment by tngTUDOR** [comment]
:penguin: :green_apple:  Using `bash` _could_ leave windows developpers out of the game.  
_BUT_ that is not an issue for the moment I guess

**Comment by tngTUDOR** [comment]
A "clean.sh" script in case we need to "restart all over again" would be handy

**Comment by cmutel** [comment]
The existing script [deletes the database](https://github.com/BONSAMURAIS/schema/blob/sql-reorg/sql/reset_db.sql#L1) before doing anything else.

**Comment by cmutel** [comment]
I don't think people would be recreating Bonsai on a personal machine, this is definitely somewhere in the cloud. Plus Windows has the Linux subsystem, I guess it should be usable there as well.

**Comment by tngTUDOR** [comment]
I have one minor suggestion, let's append to the log, instead of overwriting it. 
Like this, we can use the full log later to recreate the database if necessary

**Pull request merged**
